CREATE SEQUENCE IF NOT EXISTS product_seq start with 1000 increment by 1;

CREATE SEQUENCE IF NOT EXISTS purchase_seq start with 1 increment by 1;


create table IF NOT EXISTS user (
       id bigint generated by default as identity,
        name varchar(255),
        email varchar(255),
        dob date,
        password varchar(255),
        primary key (id)
    );

create table IF NOT EXISTS admin (
       id bigint not null,
        primary key (id)
    );

 create table IF NOT EXISTS buyer (
       id bigint not null,
        primary key (id)
    );

create table IF NOT EXISTS product (
       id bigint not null DEFAULT nextval('product_seq'),
        name varchar(255),
        description varchar(255),
        category varchar(255),
        in_stock integer not null,
        price double not null,        
        primary key (id)
    );

create table IF NOT EXISTS PURCHASE (
       id bigint not null DEFAULT nextval('purchase_seq'),
        purchase_date date,
        total double not null,
        buyer_id bigint not null,
        primary key (id)
    );


create table IF NOT EXISTS purchase_product (
       product_id bigint not null,
        purchase_id bigint not null,
        quantity integer not null,
        sub_total double not null,
        primary key (product_id, purchase_id)
    );


alter table admin 
       add constraint IF NOT EXISTS FK1ja8rua032fgnk9jmq7du3b3a 
       foreign key (id) 
       references user;

alter table buyer 
       add constraint IF NOT EXISTS FK516w53ywd7f16mktqnoo0qlyu 
       foreign key (id) 
       references user;


alter table purchase 
       add constraint IF NOT EXISTS FKb8m8lunr6ml5pv1vlurpldl9k 
       foreign key (buyer_id) 
       references buyer;

alter table purchase_product 
       add constraint IF NOT EXISTS FKl1da8u1v57wry7sunkkgmjr8o 
       foreign key (product_id) 
       references product;

alter table purchase_product 
       add constraint IF NOT EXISTS FK1te3j5efipmc5c19wve8c90qd 
       foreign key (purchase_id) 
       references purchase;


-- employee_id BIGINT NOT NULL DEFAULT nextval('employee_seq') PRIMARY KEY,
